# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 549)
        MainWindow.setMinimumSize(QtCore.QSize(1073, 549))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icon/lightning-bolt-256.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {background: #2C3E50; color: #BDC3C7;}\n"
"QWidget QLabel {font-size: 12px}\n"
"QPushButton{\n"
"    border-radius: 7px;\n"
"    border: 1px solid black;\n"
"    background: #ECF0F1;\n"
"    width: 110px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background: #7F8C8D; \n"
"    color: #BDC5C8;\n"
"    }\n"
"QPushButton:checked {\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"    background: #0F2A45;\n"
"}\n"
"QLineEdit{\n"
"    border: 2px solid #00000080;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;    \n"
"    background-color: rgba(236, 240, 241, 0.5);\n"
"    width: 125px;\n"
"    }")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoButton = QtWidgets.QLabel(self.centralwidget)
        self.logoButton.setMinimumSize(QtCore.QSize(64, 64))
        self.logoButton.setMaximumSize(QtCore.QSize(64, 64))
        self.logoButton.setStyleSheet("#Logo {background-color: #0F2A45; font-size: 12px; border: 1px solid black;  border-radius: 7px;}")
        self.logoButton.setPixmap(QtGui.QPixmap(":/icons/Icon/lightning-bolt-48.ico"))
        self.logoButton.setAlignment(QtCore.Qt.AlignCenter)
        self.logoButton.setObjectName("logoButton")
        self.verticalLayout.addWidget(self.logoButton)
        self.customerButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.customerButton.sizePolicy().hasHeightForWidth())
        self.customerButton.setSizePolicy(sizePolicy)
        self.customerButton.setMinimumSize(QtCore.QSize(64, 64))
        self.customerButton.setMaximumSize(QtCore.QSize(64, 64))
        self.customerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icon/user-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.customerButton.setIcon(icon1)
        self.customerButton.setIconSize(QtCore.QSize(64, 64))
        self.customerButton.setCheckable(True)
        self.customerButton.setChecked(True)
        self.customerButton.setObjectName("customerButton")
        self.leftBarButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.leftBarButtonGroup.setObjectName("leftBarButtonGroup")
        self.leftBarButtonGroup.addButton(self.customerButton)
        self.verticalLayout.addWidget(self.customerButton)
        self.employeeButton = QtWidgets.QPushButton(self.centralwidget)
        self.employeeButton.setMinimumSize(QtCore.QSize(64, 64))
        self.employeeButton.setMaximumSize(QtCore.QSize(64, 64))
        self.employeeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.employeeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icon/collaborator-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.employeeButton.setIcon(icon2)
        self.employeeButton.setIconSize(QtCore.QSize(32, 32))
        self.employeeButton.setCheckable(True)
        self.employeeButton.setObjectName("employeeButton")
        self.leftBarButtonGroup.addButton(self.employeeButton)
        self.verticalLayout.addWidget(self.employeeButton)
        self.supplierButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.supplierButton.sizePolicy().hasHeightForWidth())
        self.supplierButton.setSizePolicy(sizePolicy)
        self.supplierButton.setMinimumSize(QtCore.QSize(64, 64))
        self.supplierButton.setMaximumSize(QtCore.QSize(64, 64))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icon/businessman-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.supplierButton.setIcon(icon3)
        self.supplierButton.setIconSize(QtCore.QSize(64, 64))
        self.supplierButton.setCheckable(True)
        self.supplierButton.setObjectName("supplierButton")
        self.leftBarButtonGroup.addButton(self.supplierButton)
        self.verticalLayout.addWidget(self.supplierButton)
        self.buildingButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.buildingButton.sizePolicy().hasHeightForWidth())
        self.buildingButton.setSizePolicy(sizePolicy)
        self.buildingButton.setMinimumSize(QtCore.QSize(64, 64))
        self.buildingButton.setMaximumSize(QtCore.QSize(64, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icon/organization-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buildingButton.setIcon(icon4)
        self.buildingButton.setIconSize(QtCore.QSize(64, 64))
        self.buildingButton.setCheckable(True)
        self.buildingButton.setObjectName("buildingButton")
        self.leftBarButtonGroup.addButton(self.buildingButton)
        self.verticalLayout.addWidget(self.buildingButton)
        self.materialButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.materialButton.sizePolicy().hasHeightForWidth())
        self.materialButton.setSizePolicy(sizePolicy)
        self.materialButton.setMinimumSize(QtCore.QSize(64, 64))
        self.materialButton.setMaximumSize(QtCore.QSize(64, 64))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icon/month-view-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.materialButton.setIcon(icon5)
        self.materialButton.setIconSize(QtCore.QSize(64, 64))
        self.materialButton.setCheckable(True)
        self.materialButton.setObjectName("materialButton")
        self.leftBarButtonGroup.addButton(self.materialButton)
        self.verticalLayout.addWidget(self.materialButton)
        self.dateButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.dateButton.sizePolicy().hasHeightForWidth())
        self.dateButton.setSizePolicy(sizePolicy)
        self.dateButton.setMinimumSize(QtCore.QSize(64, 64))
        self.dateButton.setMaximumSize(QtCore.QSize(64, 64))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icon/date-to-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dateButton.setIcon(icon6)
        self.dateButton.setIconSize(QtCore.QSize(64, 64))
        self.dateButton.setCheckable(True)
        self.dateButton.setObjectName("dateButton")
        self.leftBarButtonGroup.addButton(self.dateButton)
        self.verticalLayout.addWidget(self.dateButton)
        self.requestButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.requestButton.sizePolicy().hasHeightForWidth())
        self.requestButton.setSizePolicy(sizePolicy)
        self.requestButton.setMinimumSize(QtCore.QSize(64, 64))
        self.requestButton.setMaximumSize(QtCore.QSize(64, 64))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icon/new-post-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.requestButton.setIcon(icon7)
        self.requestButton.setIconSize(QtCore.QSize(64, 64))
        self.requestButton.setCheckable(True)
        self.requestButton.setObjectName("requestButton")
        self.leftBarButtonGroup.addButton(self.requestButton)
        self.verticalLayout.addWidget(self.requestButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Customer = QtWidgets.QWidget()
        self.page_Customer.setObjectName("page_Customer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_Customer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(15, -1, -1, -1)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(25)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.page_Customer)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.customerName = QtWidgets.QLineEdit(self.page_Customer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerName.sizePolicy().hasHeightForWidth())
        self.customerName.setSizePolicy(sizePolicy)
        self.customerName.setObjectName("customerName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.customerName)
        self.customerLastPaternalName = QtWidgets.QLineEdit(self.page_Customer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerLastPaternalName.sizePolicy().hasHeightForWidth())
        self.customerLastPaternalName.setSizePolicy(sizePolicy)
        self.customerLastPaternalName.setObjectName("customerLastPaternalName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.customerLastPaternalName)
        self.label_3 = QtWidgets.QLabel(self.page_Customer)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.customerPhone = QtWidgets.QLineEdit(self.page_Customer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerPhone.sizePolicy().hasHeightForWidth())
        self.customerPhone.setSizePolicy(sizePolicy)
        self.customerPhone.setObjectName("customerPhone")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.customerPhone)
        self.label_4 = QtWidgets.QLabel(self.page_Customer)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.customerAddress = QtWidgets.QLineEdit(self.page_Customer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerAddress.sizePolicy().hasHeightForWidth())
        self.customerAddress.setSizePolicy(sizePolicy)
        self.customerAddress.setObjectName("customerAddress")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.customerAddress)
        self.updateCustomer = QtWidgets.QPushButton(self.page_Customer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateCustomer.setFont(font)
        self.updateCustomer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateCustomer.setStyleSheet("QPushButton {\n"
"    color: #d7a336;\n"
"}")
        self.updateCustomer.setObjectName("updateCustomer")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.updateCustomer)
        self.addCustomer = QtWidgets.QPushButton(self.page_Customer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addCustomer.sizePolicy().hasHeightForWidth())
        self.addCustomer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addCustomer.setFont(font)
        self.addCustomer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addCustomer.setStyleSheet("QPushButton {\n"
"    color: green;\n"
"}")
        self.addCustomer.setObjectName("addCustomer")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.addCustomer)
        self.deleteCustomer = QtWidgets.QPushButton(self.page_Customer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteCustomer.sizePolicy().hasHeightForWidth())
        self.deleteCustomer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteCustomer.setFont(font)
        self.deleteCustomer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteCustomer.setStyleSheet("QPushButton {\n"
"    color: red;\n"
"}")
        self.deleteCustomer.setObjectName("deleteCustomer")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.deleteCustomer)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.page_Customer)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_13 = QtWidgets.QLabel(self.page_Customer)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.customerLastMaternalName = QtWidgets.QLineEdit(self.page_Customer)
        self.customerLastMaternalName.setObjectName("customerLastMaternalName")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.customerLastMaternalName)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.customerTable = QtWidgets.QTableWidget(self.page_Customer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.customerTable.setFont(font)
        self.customerTable.setStyleSheet("    QHeaderView::section {\n"
"        background-color: #0F2A45;   /* Fondo del encabezado */\n"
"        color: white;                /* Color del texto */\n"
"        border: 1px solid #2D5986;   /* Bordes del encabezado */\n"
"        padding: 2px;\n"
"    }\n"
"\n"
"    QTableWidget::item {\n"
"        border: 1px solid #2D5986;   /* Bordes de las celdas */\n"
"        padding: 2px;                /* Espaciado dentro de las celdas */\n"
"    }\n"
"\n"
"    QTableWidget::item:alternate{\n"
"        background-color: #0B4B6C;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected {\n"
"        color: black; /*Color del texto*/\n"
"        background-color: #82ABD5;   /* Fondo cuando se selecciona */\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        border: 1px solid #031A31;   /* Bordes de la tabla */\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #000000;\n"
"        width: 16px;\n"
"    }\n"
"    \n"
"    QScrollBar::handle:vertical {\n"
"        background: #00796b;\n"
"        min-height: 20px;\n"
"    }")
        self.customerTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.customerTable.setAlternatingRowColors(True)
        self.customerTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.customerTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.customerTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.customerTable.setShowGrid(True)
        self.customerTable.setObjectName("customerTable")
        self.customerTable.setColumnCount(6)
        self.customerTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(5, item)
        self.customerTable.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.customerTable)
        self.horizontalLayout_2.setStretch(1, 2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_Customer)
        self.page_Employe = QtWidgets.QWidget()
        self.page_Employe.setObjectName("page_Employe")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_Employe)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(15, -1, -1, -1)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.page_Employe)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.employeeName = QtWidgets.QLineEdit(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeeName.sizePolicy().hasHeightForWidth())
        self.employeeName.setSizePolicy(sizePolicy)
        self.employeeName.setObjectName("employeeName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.employeeName)
        self.label_6 = QtWidgets.QLabel(self.page_Employe)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.employeePaternalLastName = QtWidgets.QLineEdit(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeePaternalLastName.sizePolicy().hasHeightForWidth())
        self.employeePaternalLastName.setSizePolicy(sizePolicy)
        self.employeePaternalLastName.setObjectName("employeePaternalLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.employeePaternalLastName)
        self.label_7 = QtWidgets.QLabel(self.page_Employe)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.employeeMaternalLastName = QtWidgets.QLineEdit(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeeMaternalLastName.sizePolicy().hasHeightForWidth())
        self.employeeMaternalLastName.setSizePolicy(sizePolicy)
        self.employeeMaternalLastName.setObjectName("employeeMaternalLastName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.employeeMaternalLastName)
        self.label_8 = QtWidgets.QLabel(self.page_Employe)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.employeePosition = QtWidgets.QComboBox(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeePosition.sizePolicy().hasHeightForWidth())
        self.employeePosition.setSizePolicy(sizePolicy)
        self.employeePosition.setObjectName("employeePosition")
        self.employeePosition.addItem("")
        self.employeePosition.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.employeePosition)
        self.label_9 = QtWidgets.QLabel(self.page_Employe)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.employeeMail = QtWidgets.QLineEdit(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeeMail.sizePolicy().hasHeightForWidth())
        self.employeeMail.setSizePolicy(sizePolicy)
        self.employeeMail.setObjectName("employeeMail")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.employeeMail)
        self.label_10 = QtWidgets.QLabel(self.page_Employe)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.employeeUsername = QtWidgets.QLineEdit(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeeUsername.sizePolicy().hasHeightForWidth())
        self.employeeUsername.setSizePolicy(sizePolicy)
        self.employeeUsername.setObjectName("employeeUsername")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.employeeUsername)
        self.label_11 = QtWidgets.QLabel(self.page_Employe)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.employeePassword = QtWidgets.QLineEdit(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeePassword.sizePolicy().hasHeightForWidth())
        self.employeePassword.setSizePolicy(sizePolicy)
        self.employeePassword.setObjectName("employeePassword")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.employeePassword)
        self.updateEmployee = QtWidgets.QPushButton(self.page_Employe)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateEmployee.setFont(font)
        self.updateEmployee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateEmployee.setStyleSheet("QPushButton {\n"
"    color: #d7a336;\n"
"}")
        self.updateEmployee.setObjectName("updateEmployee")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.updateEmployee)
        self.addEmployee = QtWidgets.QPushButton(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addEmployee.sizePolicy().hasHeightForWidth())
        self.addEmployee.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addEmployee.setFont(font)
        self.addEmployee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addEmployee.setStyleSheet("QPushButton {\n"
"    color: green;\n"
"}")
        self.addEmployee.setObjectName("addEmployee")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.addEmployee)
        self.deleteEmployee = QtWidgets.QPushButton(self.page_Employe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteEmployee.sizePolicy().hasHeightForWidth())
        self.deleteEmployee.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteEmployee.setFont(font)
        self.deleteEmployee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteEmployee.setStyleSheet("QPushButton {\n"
"    color: red;\n"
"}")
        self.deleteEmployee.setObjectName("deleteEmployee")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.deleteEmployee)
        self.label_12 = QtWidgets.QLabel(self.page_Employe)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.employeeBuilding = QtWidgets.QLineEdit(self.page_Employe)
        self.employeeBuilding.setObjectName("employeeBuilding")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.employeeBuilding)
        self.horizontalLayout.addLayout(self.formLayout)
        self.employeeTable = QtWidgets.QTableWidget(self.page_Employe)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeeTable.setFont(font)
        self.employeeTable.setStyleSheet("    QHeaderView::section {\n"
"        background-color: #0F2A45;   /* Fondo del encabezado */\n"
"        color: white;                /* Color del texto */\n"
"        border: 1px solid #2D5986;   /* Bordes del encabezado */\n"
"        padding: 2px;\n"
"    }\n"
"\n"
"    QTableWidget::item {\n"
"        border: 1px solid #2D5986;   /* Bordes de las celdas */\n"
"        padding: 2px;                /* Espaciado dentro de las celdas */\n"
"    }\n"
"\n"
"    QTableWidget::item:alternate{\n"
"        background-color: #0B4B6C;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected {\n"
"        color: black; /*Color del texto*/\n"
"        background-color: #82ABD5;   /* Fondo cuando se selecciona */\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        border: 1px solid #031A31;   /* Bordes de la tabla */\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #000000;\n"
"        width: 16px;\n"
"    }\n"
"    \n"
"    QScrollBar::handle:vertical {\n"
"        background: #00796b;\n"
"        min-height: 20px;\n"
"    }")
        self.employeeTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.employeeTable.setAlternatingRowColors(True)
        self.employeeTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.employeeTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.employeeTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.employeeTable.setShowGrid(True)
        self.employeeTable.setObjectName("employeeTable")
        self.employeeTable.setColumnCount(9)
        self.employeeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(8, item)
        self.employeeTable.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.employeeTable)
        self.horizontalLayout.setStretch(1, 2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_Employe)
        self.page_Suplier = QtWidgets.QWidget()
        self.page_Suplier.setObjectName("page_Suplier")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_Suplier)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 991, 531))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(15, 10, -1, -1)
        self.formLayout_4.setHorizontalSpacing(0)
        self.formLayout_4.setVerticalSpacing(25)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.suplierName = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suplierName.sizePolicy().hasHeightForWidth())
        self.suplierName.setSizePolicy(sizePolicy)
        self.suplierName.setObjectName("suplierName")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.suplierName)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.suplierNumber = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suplierNumber.sizePolicy().hasHeightForWidth())
        self.suplierNumber.setSizePolicy(sizePolicy)
        self.suplierNumber.setObjectName("suplierNumber")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.suplierNumber)
        self.updateSuplier = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateSuplier.setFont(font)
        self.updateSuplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateSuplier.setStyleSheet("QPushButton {\n"
"    color: #d7a336;\n"
"}")
        self.updateSuplier.setObjectName("updateSuplier")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.updateSuplier)
        self.addSuplier = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addSuplier.sizePolicy().hasHeightForWidth())
        self.addSuplier.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addSuplier.setFont(font)
        self.addSuplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addSuplier.setStyleSheet("QPushButton {\n"
"    color: green;\n"
"}")
        self.addSuplier.setObjectName("addSuplier")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.addSuplier)
        self.deleteSuplier = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteSuplier.sizePolicy().hasHeightForWidth())
        self.deleteSuplier.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteSuplier.setFont(font)
        self.deleteSuplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteSuplier.setStyleSheet("QPushButton {\n"
"    color: red;\n"
"}")
        self.deleteSuplier.setObjectName("deleteSuplier")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.deleteSuplier)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.suplierTable = QtWidgets.QTableWidget(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.suplierTable.setFont(font)
        self.suplierTable.setStyleSheet("    QHeaderView::section {\n"
"        background-color: #0F2A45;   /* Fondo del encabezado */\n"
"        color: white;                /* Color del texto */\n"
"        border: 1px solid #2D5986;   /* Bordes del encabezado */\n"
"        padding: 2px;\n"
"    }\n"
"\n"
"    QTableWidget::item {\n"
"        border: 1px solid #2D5986;   /* Bordes de las celdas */\n"
"        padding: 2px;                /* Espaciado dentro de las celdas */\n"
"    }\n"
"\n"
"    QTableWidget::item:alternate{\n"
"        background-color: #0B4B6C;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected {\n"
"        color: black; /*Color del texto*/\n"
"        background-color: #82ABD5;   /* Fondo cuando se selecciona */\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        border: 1px solid #031A31;   /* Bordes de la tabla */\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #000000;\n"
"        width: 16px;\n"
"    }\n"
"    \n"
"    QScrollBar::handle:vertical {\n"
"        background: #00796b;\n"
"        min-height: 20px;\n"
"    }")
        self.suplierTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.suplierTable.setAlternatingRowColors(True)
        self.suplierTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.suplierTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.suplierTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.suplierTable.setShowGrid(True)
        self.suplierTable.setObjectName("suplierTable")
        self.suplierTable.setColumnCount(3)
        self.suplierTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.suplierTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.suplierTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.suplierTable.setHorizontalHeaderItem(2, item)
        self.suplierTable.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.suplierTable)
        self.horizontalLayout_4.setStretch(1, 2)
        self.stackedWidget.addWidget(self.page_Suplier)
        self.page_Building = QtWidgets.QWidget()
        self.page_Building.setObjectName("page_Building")
        self.layoutWidget = QtWidgets.QWidget(self.page_Building)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(15, 10, -1, -1)
        self.formLayout_3.setHorizontalSpacing(0)
        self.formLayout_3.setVerticalSpacing(25)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.buildingProyect = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildingProyect.sizePolicy().hasHeightForWidth())
        self.buildingProyect.setSizePolicy(sizePolicy)
        self.buildingProyect.setObjectName("buildingProyect")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.buildingProyect)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.buildingAddress = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildingAddress.sizePolicy().hasHeightForWidth())
        self.buildingAddress.setSizePolicy(sizePolicy)
        self.buildingAddress.setObjectName("buildingAddress")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buildingAddress)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.buildindgDate = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildindgDate.sizePolicy().hasHeightForWidth())
        self.buildindgDate.setSizePolicy(sizePolicy)
        self.buildindgDate.setObjectName("buildindgDate")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.buildindgDate)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.buildingCustomer = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildingCustomer.sizePolicy().hasHeightForWidth())
        self.buildingCustomer.setSizePolicy(sizePolicy)
        self.buildingCustomer.setObjectName("buildingCustomer")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buildingCustomer)
        self.updateBuilding = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateBuilding.setFont(font)
        self.updateBuilding.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateBuilding.setStyleSheet("QPushButton {\n"
"    color: #d7a336;\n"
"}")
        self.updateBuilding.setObjectName("updateBuilding")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.updateBuilding)
        self.addBuilding = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBuilding.sizePolicy().hasHeightForWidth())
        self.addBuilding.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addBuilding.setFont(font)
        self.addBuilding.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBuilding.setStyleSheet("QPushButton {\n"
"    color: green;\n"
"}")
        self.addBuilding.setObjectName("addBuilding")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.addBuilding)
        self.deleteBuilding = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteBuilding.sizePolicy().hasHeightForWidth())
        self.deleteBuilding.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteBuilding.setFont(font)
        self.deleteBuilding.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteBuilding.setStyleSheet("QPushButton {\n"
"    color: red;\n"
"}")
        self.deleteBuilding.setObjectName("deleteBuilding")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.deleteBuilding)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.buildingTable = QtWidgets.QTableWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buildingTable.setFont(font)
        self.buildingTable.setStyleSheet("    QHeaderView::section {\n"
"        background-color: #0F2A45;   /* Fondo del encabezado */\n"
"        color: white;                /* Color del texto */\n"
"        border: 1px solid #2D5986;   /* Bordes del encabezado */\n"
"        padding: 2px;\n"
"    }\n"
"\n"
"    QTableWidget::item {\n"
"        border: 1px solid #2D5986;   /* Bordes de las celdas */\n"
"        padding: 2px;                /* Espaciado dentro de las celdas */\n"
"    }\n"
"\n"
"    QTableWidget::item:alternate{\n"
"        background-color: #0B4B6C;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected {\n"
"        color: black; /*Color del texto*/\n"
"        background-color: #82ABD5;   /* Fondo cuando se selecciona */\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        border: 1px solid #031A31;   /* Bordes de la tabla */\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #000000;\n"
"        width: 16px;\n"
"    }\n"
"    \n"
"    QScrollBar::handle:vertical {\n"
"        background: #00796b;\n"
"        min-height: 20px;\n"
"    }")
        self.buildingTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.buildingTable.setAlternatingRowColors(True)
        self.buildingTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.buildingTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.buildingTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.buildingTable.setShowGrid(True)
        self.buildingTable.setObjectName("buildingTable")
        self.buildingTable.setColumnCount(5)
        self.buildingTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.buildingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.buildingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.buildingTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.buildingTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.buildingTable.setHorizontalHeaderItem(4, item)
        self.buildingTable.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.buildingTable)
        self.horizontalLayout_3.setStretch(1, 2)
        self.stackedWidget.addWidget(self.page_Building)
        self.page_Material = QtWidgets.QWidget()
        self.page_Material.setObjectName("page_Material")
        self.layoutWidget_3 = QtWidgets.QWidget(self.page_Material)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 991, 531))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setContentsMargins(15, 10, -1, -1)
        self.formLayout_5.setHorizontalSpacing(0)
        self.formLayout_5.setVerticalSpacing(25)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.materialName = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialName.sizePolicy().hasHeightForWidth())
        self.materialName.setSizePolicy(sizePolicy)
        self.materialName.setObjectName("materialName")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.materialName)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.materialCant = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialCant.sizePolicy().hasHeightForWidth())
        self.materialCant.setSizePolicy(sizePolicy)
        self.materialCant.setObjectName("materialCant")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.materialCant)
        self.updateMaterial = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateMaterial.setFont(font)
        self.updateMaterial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateMaterial.setStyleSheet("QPushButton {\n"
"    color: #d7a336;\n"
"}")
        self.updateMaterial.setObjectName("updateMaterial")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.updateMaterial)
        self.addMaterial = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMaterial.sizePolicy().hasHeightForWidth())
        self.addMaterial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addMaterial.setFont(font)
        self.addMaterial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addMaterial.setStyleSheet("QPushButton {\n"
"    color: green;\n"
"}")
        self.addMaterial.setObjectName("addMaterial")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.addMaterial)
        self.deleteMaterial = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteMaterial.sizePolicy().hasHeightForWidth())
        self.deleteMaterial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteMaterial.setFont(font)
        self.deleteMaterial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteMaterial.setStyleSheet("QPushButton {\n"
"    color: red;\n"
"}")
        self.deleteMaterial.setObjectName("deleteMaterial")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.deleteMaterial)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        self.materialTable = QtWidgets.QTableWidget(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.materialTable.setFont(font)
        self.materialTable.setStyleSheet("    QHeaderView::section {\n"
"        background-color: #0F2A45;   /* Fondo del encabezado */\n"
"        color: white;                /* Color del texto */\n"
"        border: 1px solid #2D5986;   /* Bordes del encabezado */\n"
"        padding: 2px;\n"
"    }\n"
"\n"
"    QTableWidget::item {\n"
"        border: 1px solid #2D5986;   /* Bordes de las celdas */\n"
"        padding: 2px;                /* Espaciado dentro de las celdas */\n"
"    }\n"
"\n"
"    QTableWidget::item:alternate{\n"
"        background-color: #0B4B6C;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected {\n"
"        color: black; /*Color del texto*/\n"
"        background-color: #82ABD5;   /* Fondo cuando se selecciona */\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        border: 1px solid #031A31;   /* Bordes de la tabla */\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #000000;\n"
"        width: 16px;\n"
"    }\n"
"    \n"
"    QScrollBar::handle:vertical {\n"
"        background: #00796b;\n"
"        min-height: 20px;\n"
"    }")
        self.materialTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.materialTable.setAlternatingRowColors(True)
        self.materialTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.materialTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.materialTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.materialTable.setShowGrid(True)
        self.materialTable.setObjectName("materialTable")
        self.materialTable.setColumnCount(4)
        self.materialTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.materialTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialTable.setHorizontalHeaderItem(3, item)
        self.materialTable.verticalHeader().setVisible(False)
        self.horizontalLayout_5.addWidget(self.materialTable)
        self.horizontalLayout_5.setStretch(1, 2)
        self.stackedWidget.addWidget(self.page_Material)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.customerButton, self.employeeButton)
        MainWindow.setTabOrder(self.employeeButton, self.supplierButton)
        MainWindow.setTabOrder(self.supplierButton, self.buildingButton)
        MainWindow.setTabOrder(self.buildingButton, self.materialButton)
        MainWindow.setTabOrder(self.materialButton, self.dateButton)
        MainWindow.setTabOrder(self.dateButton, self.requestButton)
        MainWindow.setTabOrder(self.requestButton, self.customerName)
        MainWindow.setTabOrder(self.customerName, self.customerLastPaternalName)
        MainWindow.setTabOrder(self.customerLastPaternalName, self.customerLastMaternalName)
        MainWindow.setTabOrder(self.customerLastMaternalName, self.customerPhone)
        MainWindow.setTabOrder(self.customerPhone, self.customerAddress)
        MainWindow.setTabOrder(self.customerAddress, self.updateCustomer)
        MainWindow.setTabOrder(self.updateCustomer, self.addCustomer)
        MainWindow.setTabOrder(self.addCustomer, self.deleteCustomer)
        MainWindow.setTabOrder(self.deleteCustomer, self.customerTable)
        MainWindow.setTabOrder(self.customerTable, self.employeeName)
        MainWindow.setTabOrder(self.employeeName, self.employeePaternalLastName)
        MainWindow.setTabOrder(self.employeePaternalLastName, self.employeeMaternalLastName)
        MainWindow.setTabOrder(self.employeeMaternalLastName, self.employeePosition)
        MainWindow.setTabOrder(self.employeePosition, self.employeeMail)
        MainWindow.setTabOrder(self.employeeMail, self.employeeUsername)
        MainWindow.setTabOrder(self.employeeUsername, self.employeePassword)
        MainWindow.setTabOrder(self.employeePassword, self.employeeBuilding)
        MainWindow.setTabOrder(self.employeeBuilding, self.updateEmployee)
        MainWindow.setTabOrder(self.updateEmployee, self.addEmployee)
        MainWindow.setTabOrder(self.addEmployee, self.deleteEmployee)
        MainWindow.setTabOrder(self.deleteEmployee, self.employeeTable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Constructura Electrica"))
        self.customerButton.setToolTip(_translate("MainWindow", "Clientes"))
        self.employeeButton.setToolTip(_translate("MainWindow", "Empleados"))
        self.supplierButton.setToolTip(_translate("MainWindow", "Proveedores"))
        self.buildingButton.setToolTip(_translate("MainWindow", "Obras"))
        self.materialButton.setToolTip(_translate("MainWindow", "Materiales"))
        self.dateButton.setToolTip(_translate("MainWindow", "Citas"))
        self.requestButton.setToolTip(_translate("MainWindow", "Pedidos"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.label_3.setText(_translate("MainWindow", "Telefono"))
        self.label_4.setText(_translate("MainWindow", "Direccion"))
        self.updateCustomer.setText(_translate("MainWindow", "Actualizar"))
        self.addCustomer.setText(_translate("MainWindow", "Agregar"))
        self.deleteCustomer.setText(_translate("MainWindow", "Eliminar"))
        self.label_2.setText(_translate("MainWindow", "Apellido Paterno"))
        self.label_13.setText(_translate("MainWindow", "Apellido Materno:"))
        self.customerTable.setSortingEnabled(True)
        item = self.customerTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.customerTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.customerTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellido P"))
        item = self.customerTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Apellido M"))
        item = self.customerTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Direccion"))
        item = self.customerTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Telefono"))
        self.label_5.setText(_translate("MainWindow", "Nombre"))
        self.label_6.setText(_translate("MainWindow", "Apellido Paterno"))
        self.label_7.setText(_translate("MainWindow", "Apellido Materno"))
        self.label_8.setText(_translate("MainWindow", "Puesto"))
        self.employeePosition.setItemText(0, _translate("MainWindow", "Trabajador"))
        self.employeePosition.setItemText(1, _translate("MainWindow", "Administrador"))
        self.label_9.setText(_translate("MainWindow", "Email"))
        self.label_10.setText(_translate("MainWindow", "Usuario"))
        self.label_11.setText(_translate("MainWindow", "Contraseña"))
        self.updateEmployee.setText(_translate("MainWindow", "Actualizar"))
        self.addEmployee.setText(_translate("MainWindow", "Agregar"))
        self.deleteEmployee.setText(_translate("MainWindow", "Eliminar"))
        self.label_12.setText(_translate("MainWindow", "Obra"))
        self.employeeTable.setSortingEnabled(True)
        item = self.employeeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.employeeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.employeeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellido paterno"))
        item = self.employeeTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Apellido materno"))
        item = self.employeeTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.employeeTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Puesto"))
        item = self.employeeTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Usuario"))
        item = self.employeeTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Contraseña"))
        item = self.employeeTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Obra"))
        self.label_17.setText(_translate("MainWindow", "Nombre"))
        self.label_19.setText(_translate("MainWindow", "Telefono"))
        self.updateSuplier.setText(_translate("MainWindow", "Actualizar"))
        self.addSuplier.setText(_translate("MainWindow", "Agregar"))
        self.deleteSuplier.setText(_translate("MainWindow", "Eliminar"))
        self.suplierTable.setSortingEnabled(True)
        item = self.suplierTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.suplierTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.suplierTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Telefono"))
        self.label_14.setText(_translate("MainWindow", "Proyecto"))
        self.label_15.setText(_translate("MainWindow", "Direccion"))
        self.label_16.setText(_translate("MainWindow", "Fecha de inicio"))
        self.label_18.setText(_translate("MainWindow", "Cliente"))
        self.updateBuilding.setText(_translate("MainWindow", "Actualizar"))
        self.addBuilding.setText(_translate("MainWindow", "Agregar"))
        self.deleteBuilding.setText(_translate("MainWindow", "Eliminar"))
        self.buildingTable.setSortingEnabled(True)
        item = self.buildingTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.buildingTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Proyecto"))
        item = self.buildingTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ubicacion"))
        item = self.buildingTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fecha de inicio"))
        item = self.buildingTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cliente"))
        self.label_20.setText(_translate("MainWindow", "Material"))
        self.label_21.setText(_translate("MainWindow", "Cantidad"))
        self.updateMaterial.setText(_translate("MainWindow", "Actualizar"))
        self.addMaterial.setText(_translate("MainWindow", "Agregar"))
        self.deleteMaterial.setText(_translate("MainWindow", "Eliminar"))
        self.materialTable.setSortingEnabled(True)
        item = self.materialTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.materialTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.materialTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.materialTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Provedor"))
import resources_rc
